#!/bin/sh -e
#DEBHELPER#
case "$1" in
    configure)
        if ! id -u catpuppet >/dev/null 2>&1; then
            adduser --system --group --home /usr/lib/catpuppetbridge \
                --disabled-login --shell /usr/sbin/nologin \
                catpuppet
        fi
    ;;
esac

exit 0
